export const columns = [
  { field: "id", headerName: "ID", width: 50 },
  { field: "name", headerName: "Name", flex: 1 },
  { field: "phoneNumber", headerName: "Phone Number", flex: 1 },
  { field: "email", headerName: "Email", flex: 1 },
  { field: "cost", headerName: "Cost", flex: 1 },
  { field: "date", headerName: "Date", flex: 1 },
];
export const rows = [
  {
    id: 1,
    name: "Jon Snow",
    phoneNumber: "(665)121-5454",
    email: "jonsnow@gmail.com",
    cost: "$",
    date: "2023-01-01",
  },
  {
    id: 2,
    name: "Cersei Lannister",
    phoneNumber: "(421)314-2288",
    email: "cerseilannister@gmail.com",
    cost: "$",
    date: "2023-01-02",
  },
  {
    id: 3,
    name: "Jaime Lannister",
    phoneNumber: "(422)982-6739",
    email: "jaimelannister@gmail.com",
    cost: "$",
    date: "2023-01-03",
  },
  {
    id: 4,
    name: "Anya Stark",
    phoneNumber: "(921)425-6742",
    email: "anyastark@gmail.com",
    cost: "$",
    date: "2023-01-04",
  },
  {
    id: 5,
    name: "Daenerys Targaryen",
    phoneNumber: "(421)445-1189",
    email: "daenerystargaryen@gmail.com",
    cost: "$",
    date: "2023-01-05",
  },
  {
    id: 6,
    name: "Ever Melisandre",
    phoneNumber: "(232)545-6483",
    email: "evermelisandre@gmail.com",
    cost: "$",
    date: "2023-01-06",
  },
  {
    id: 7,
    name: "Ferrara Clifford",
    phoneNumber: "(543)124-0123",
    email: "ferraraclifford@gmail.com",
    cost: "$",
    date: "2023-01-07",
  },
  {
    id: 8,
    name: "Rossini Frances",
    phoneNumber: "(222)444-5555",
    email: "rossinifrances@gmail.com",
    cost: "$",
    date: "2023-01-08",
  },
  {
    id: 9,
    name: "Harvey Roxie",
    phoneNumber: "(444)555-6239",
    email: "harveyroxie@gmail.com",
    cost: "$",
    date: "2023-01-09",
  },
];
