export const rows = [
  {
    id: 1,
    ID: "1",
    name: "Jon Snow",
    email: "YlQ7a@example.com",
    age: "20",
    phone: "1234567666",
    access: "Admin",
  },
  {
    id: 2,
    ID: "2",
    name: "Cersei Lannister",
    email: "YlQ7a@example.com",
    age: "45",
    phone: "1834567890",
    access: "Admin",
  },
  {
    id: 3,
    ID: "3",
    name: "Jaime Lannister",
    email: "YlQ7a@example.com",
    age: "42",
    phone: "4234567890",
    access: "Admin",
  },
  {
    id: 4,
    ID: "4",
    name: "Arya Stark",
    email: "YlQ7a@example.com",
    age: "31",
    phone: "0234567222",
    access: "Manager",
  },
  {
    id: 5,
    ID: "5",
    name: "Daenerys Targaryen",
    email: "YlQ7a@example.com",
    age: "33",
    phone: "8734567890",
    access: "Manager",
  },
  {
    id: 6,
    ID: "6",
    name: "Tyrion Lannister",
    email: "YlQ7a@example.com",
    age: "59",
    phone: "1674567890",
    access: "User",
  },
  {
    id: 7,
    ID: "7",
    name: "Samwell Tarly",
    email: "YlQ7a@example.com",
    age: "45",
    phone: "4434567890",
    access: "User",
  },
  {
    id: 8,
    ID: "8",
    name: "Joffrey Baratheon",
    email: "YlQ7a@example.com",
    age: "32",
    phone: "1234567890",
    access: "User",
  },
  {
    id: 9,
    ID: "9",
    name: "Bran Stark",
    email: "YlQ7a@example.com",
    age: "25",
    phone: "1234567896",
    access: "User",
  },
];


